apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: quickmeet-victorimmanuel-me
  namespace: quickmeet
spec:
  secretName: quickmeet-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - quickmeet.victorimmanuel.me
    - api.quickmeet.victorimmanuel.me
